apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml
  - namespace.yaml
