resources:
  - homeassistant/deployment.yaml
  - homeassistant/service.yaml
  - homeassistant/config.yaml
  - homeassistant/http.yaml
  - homeassistant/pvc.yaml
  - mqtt/deployment.yaml
  - mqtt/config.yaml
  - mqtt/service.yaml
  - whisper/deployment.yaml
  - whisper/service.yaml
  - matter/deployment.yaml
  - matter/pvc.yaml
  - openthread/deployment.yaml
