apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/keycloak
  KC_HOSTNAME: keycloak.bergtobias.com
  KC_HOSTNAME_STRICT: "false"
