apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: smarthome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        ha-stack: "true"
      containers:
        - name: otbr
          image: ghcr.io/home-assistant-libs/otbr:latest
          securityContext:
            privileged: true
          env:
            - name: OTBR_INFRA_IF_NAME
              value: eth0
            - name: OTBR_RADIO_URL
              value: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: dbus
              mountPath: /var/run/dbus/system_bus_socket
              readOnly: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: dbus
          hostPath:
            path: /var/run/dbus/system_bus_socket
            type: Socket
