apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: smarthome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        ha-stack: "true"
      containers:
        - name: otbr
          image: openthread/border-router:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OT_RCP_DEVICE
              value: "spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200"
            - name: OT_INFRA_IF
              value: "eth0"
            - name: OT_THREAD_IF
              value: "wpan0"
            - name: OT_REST_LISTEN_ADDR
              value: "0.0.0.0"
            - name: OT_REST_LISTEN_PORT
              value: "8081"
            - name: OT_LOG_LEVEL
              value: "5"
          volumeMounts:
            - name: skyconnect
              mountPath: /dev/ttyACM0
            - name: tun
              mountPath: /dev/net/tun
            - name: data
              mountPath: /data
      volumes:
        - name: skyconnect
          hostPath:
            path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_008ecfc2048dec119f3674e883c5466d-if00-port0
            type: CharDevice
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: data
          hostPath:
            path: /docker-data/otbr
            type: DirectoryOrCreate
