apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        ha-stack: "true"
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:stable
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
          ports:
            - containerPort: 5580
              protocol: TCP
          volumeMounts:
            - name: matter-data
              mountPath: /data
          env:
            - name: MATTER_SERVER_STORAGE_PATH
              value: /data
      volumes:
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-server-pvc
